name: Build and release
on: [push, pull_request]

jobs:

  publish_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 21
    - name: install dependencies
      run: npm install --legacy-peer-deps
    - name: build
      run: npm run build
    - name: package
      run: npm run package
    - name: cek
      run: ls dist
    # - name: Delete drafts
    #   uses: hugo19941994/delete-draft-releases@v0.1.0
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - uses: dev-drprasad/delete-tag-and-release@v0.1.2
    #   with:
    #     delete_release: true # default: false
    #     tag_name: linux # tag name to delete
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

  # publish_on_mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 21
  #   - name: install dependencies
  #     run: npm install
  #   - name: build
  #     run: npm run build
  #   - name: publish
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: npm run publish
      
  # publish_on_win:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v2       
  #   - uses: actions/setup-node@master
  #     with:
  #       node-version: 21
  #   - name: install dependencies
  #     run: npm install
  #   - name: build
  #     run: npm run build
  #   - name: publish
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     run: npm run publish