name: Build and release
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Electron build and release
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build project
      run: npm run build
      env:
        NEXT_PUBLIC_PRIVY_APP_ID: ${{ secrets.NEXT_PUBLIC_PRIVY_APP_ID }}
    - name: Package
      run: npm run package
      
    - name: Archive build files
      if: runner.os == 'Linux'
      run: zip -r build-linux.zip ./dist

    - name: Archive build files
      if: runner.os == 'Windows'
      run: Compress-Archive -Path .\dist\* -DestinationPath build-windows.zip

    - name: Archive build files
      if: runner.os == 'macOS'
      run: zip -r build-macos.zip ./dist

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-${{ matrix.os }}
        path: build-*.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-ubuntu-latest
        path: ./builds

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-windows-latest
        path: ./builds

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-macos-latest
        path: ./builds
    - name: Extract tag name
      id: extract_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        body: |
          Release notes for ${{ env.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload Linux build asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./builds/build-linux.zip
        asset_name: build-linux.zip
        asset_content_type: application/zip

    - name: Upload Windows build asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./builds/build-windows.zip
        asset_name: build-windows.zip
        asset_content_type: application/zip

    - name: Upload macOS build asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./builds/build-macos.zip
        asset_name: build-macos.zip
        asset_content_type: application/zip